/*
  Copyright (c), 2001-2024, Shenshu Tech. Co., Ltd.
 */
#ifndef CRYPTO_FEATURES_H
#define CRYPTO_FEATURES_H

/*
 * TRNG Configuration
 */
#define CONFIG_TRNG_SUPPORT 1

/*
 * Symc Configuration
 */
#define CONFIG_SYMC_SUPPORT 1
#define CONFIG_SYMC_CCM_SUPPORT 1
#define CONFIG_SYMC_GCM_SUPPORT 1
#define CONFIG_SYMC_CMAC_SUPPORT 1
#define CONFIG_SYMC_CBC_MAC_SUPPORT 1
#define CONFIG_SYMC_CTR_NON_ALIGN_SUPPORT 1
#define CONFIG_SYMC_PROC_SUPPORT 1
#define CONFIG_SYMC_IRQ_SUPPORT 1
#define CONFIG_SYMC_128_SUPPORT 1
#define CONFIG_SYMC_256_SUPPORT 1
// #define CONFIG_SYMC_MODE_ECB_SUPPORT 1
#define CONFIG_SYMC_MODE_CTR_SUPPORT 1
#define CONFIG_SYMC_MODE_OFB_SUPPORT 1
#define CONFIG_SYMC_MODE_CFB_SUPPORT 1
#define CONFIG_SYMC_MODE_CCM_SUPPORT 1
#define CONFIG_SYMC_MODE_GCM_SUPPORT 1
#define CONFIG_SYMC_MODE_CBC_MAC_SUPPORT 1
#define CONFIG_SYMC_MODE_CMAC_SUPPORT 1
#define CONFIG_SYMC_ALG_SM4_SUPPORT 1
#define CONFIG_SYMC_BIT_WIDTH_64_SUPPORT 1
#define CONFIG_SYMC_BIT_WIDTH_8_SUPPORT 1
#define CONFIG_SYMC_SM4_MAC_SUPPORT 1

/*
 * Hash Configuration
 */
#define CONFIG_HASH_SUPPORT 1
#define CONFIG_HASH_PBKDF2_SUPPORT 1

#define CONFIG_HASH_CLONE_SUPPORT 1
#define CONFIG_HASH_HMAC_KEYSLOT_SUPPORT 1
#define CONFIG_HASH_SOFT_HMAC_SUPPORT 1
#define CONFIG_HASH_SHA256_SUPPORT 1
#define CONFIG_HASH_SM3_SUPPORT 1

/*
 * FAPC Configuration
 */

/*
 * KM Configuration
 */
#define CONFIG_KM_SUPPORT 1
#define CONFIG_KM_CLEAR_KEY_SUPPORT 1
#define CONFIG_KM_KEY_LEN_192_SUPPORT 1
#define CONFIG_KM_KEY_LEN_256_SUPPORT 1
#define CONFIG_KM_KDF_SM3_SUPPORT 1

/*
 * KM RootKey support
 */
#define CONFIG_KM_ERK_TEE_SUPPORT 1
#define CONFIG_KM_ERK_REE_SUPPORT 1
#define CONFIG_KM_ERK1_REE_SUPPORT 1
#define CONFIG_KM_ERK2_REE_SUPPORT 1

/*
 * OTP Configuration
 */
#define CONFIG_OTP_SUPPORT 1
#define CONFIG_OTP_READ_BYTE_SUPPORT 1
#define CONFIG_OTP_WRITE_BYTE_SUPPORT 1
#define CONFIG_OTP_GET_DIE_ID_SUPPORT 1
#define CONFIG_OTP_MEMORY_MAX_ADDR 0x1ff

/*
 * PKE Configuration
 */
#define CONFIG_PKE_SUPPORT 1

/*
 * PKE Cal Configuration
 */
#define CONFIG_PKE_CAL_SUPPORT 1
#define CONFIG_DRV_PKE_CAL_SUPPORT 1
#define CONFIG_PKE_EXP_MOD_SUPPORT 1
#define CONFIG_PKE_MOD_SUPPORT 1

/*
 * PKE RSA Configuration
 */
#define CONFIG_PKE_RSA_SUPPORT 1
#define CONFIG_PKE_RSA_SIGN_SUPPORT 1
#define CONFIG_PKE_RSA_VERIFY_SUPPORT 1
#define CONFIG_PKE_RSA_PUB_ENC_SUPPORT 1
#define CONFIG_PKE_RSA_PRIV_DEC_SUPPORT 1
// #define CONFIG_PKE_RSA_V15_SUPPORT 1
#define CONFIG_PKE_RSA_V21_SUPPORT 1
#define CONFIG_PKE_RSA_3072_SUPPORT 1
#define CONFIG_PKE_RSA_4096_SUPPORT 1
#define CONFIG_PKE_RSA_SHA256_SUPPORT 1

/*
 * PKE ECC Configuration
 */
#define CONFIG_PKE_ECC_SUPPORT 1

/*
 * ECC Curve Type Configuration
 */
#define CONFIG_PKE_SUPPORT_ECC_BP256R 1
#define CONFIG_PKE_SUPPORT_ECC_BP384R 1
#define CONFIG_PKE_SUPPORT_ECC_BP512R 1
#define CONFIG_PKE_SUPPORT_SM2 1
// #define CONFIG_PKE_SUPPORT_ECC_FIPS_P256R 1
// #define CONFIG_PKE_SUPPORT_ECC_FIPS_P384R 1
// #define CONFIG_PKE_SUPPORT_ECC_FIPS_P521R 1
#define CONFIG_PKE_ECC_CHECK_DOT_ON_CURVE_SUPPORT 1
#define CONFIG_PKE_ECC_ECDSA_SIGN_SUPPORT 1
#define CONFIG_PKE_ECC_ECDSA_VERIFY_SUPPORT 1
#define CONFIG_PKE_ECC_SM2_DSA_HASH_SUPPORT 1
#define CONFIG_PKE_ECC_SM2_SIGN_SUPPORT 1
#define CONFIG_PKE_ECC_SM2_VERIFY_SUPPORT 1
#define CONFIG_PKE_ECC_ECDH_SUPPORT 1
#define CONFIG_PKE_ECC_GEN_KEY_SUPPORT 1
#define CONFIG_PKE_ECC_SM2_PUB_ENC_SUPPORT 1
#define CONFIG_PKE_ECC_SM2_PRIV_DEC_SUPPORT 1
#define CONFIG_PKE_TRNG_SUPPORT 1
#define CONFIG_PKE_CAL_HASH_SUPPORT 1

/*
 * UAPI Layer Configuration
 */
#define CONFIG_UAPI_SUPPORT 1
#define CONFIG_UAPI_HASH_SUPPORT 1
#define CONFIG_UAPI_KDF_SUPPORT 1
#define CONFIG_UAPI_KM_SUPPORT 1
#define CONFIG_UAPI_OTP_SUPPORT 1
#define CONFIG_UAPI_PKE_SUPPORT 1
#define CONFIG_UAPI_SYMC_SUPPORT 1
#define CONFIG_UAPI_TRNG_SUPPORT 1

/*
 * DISPATCH Layer Configuration
 */
#define CONFIG_DISPATCH_SUPPORT 1

/*
 * KAPI Layer Configuration
 */
#define CONFIG_KAPI_SUPPORT 1
#define CONFIG_KAPI_SYMC_SUPPORT 1
#define CONFIG_SYMC_KAPI_DMA_BUF_LEN 4096
#define CONFIG_KAPI_PKE_SUPPORT 1
#define CONFIG_KAPI_HASH_SUPPORT 1
#define CONFIG_HASH_KAPI_DMA_BUF_LEN 4096
#define CONFIG_KAPI_TRNG_SUPPORT 1
#define CONFIG_MAX_PROCESS_NUM 2
#define CONFIG_DRV_AAD_SIZE 1024
#define CONFIG_KAPI_KM_SUPPORT 1
#define CONFIG_KAPI_OTP_SUPPORT 1

/*
 * DRV Layer Configuration
 */
#define CONFIG_DRV_SYMC_SUPPORT 1
#define CONFIG_DRV_PKE_SUPPORT 1
#define CONFIG_DRV_HASH_SUPPORT 1
#define CONFIG_DRV_TRNG_SUPPORT 1
#define CONFIG_DRV_KM_SUPPORT 1
#define CONFIG_DRV_OTP_SUPPORT 1

/*
 * HAL Layer Configuration
 */
#define CONFIG_HAL_TRNG_V4_SUPPORT 1
#define CONFIG_HAL_SPACC_V4_SUPPORT 1
#define CONFIG_HAL_PKE_V5_SUPPORT 1
#define CONFIG_PKE_ROM_LIB_START_ADDR 0xC00000
#define CONFIG_HAL_KM_V4_SUPPORT 1

/*
 * Parameters Configuration
 */
#define CONFIG_MMU_SUPPORT 1
#define CONFIG_SYMC_HARD_CHN_CNT 3
#define CONFIG_SYMC_HARD_CHANNEL_MASK 0xFFFF
#define CONFIG_HASH_HARD_CHN_CNT 3
#define CONFIG_HASH_HARD_CHN_MASK 0xFFFF

/*
 * Timeout Parameters Configuration
 */
#define CONFIG_HASH_CLEAR_CHN_TIMEOUT 10000
#define CONFIG_HASH_CALC_TIMEOUT 1000000
#define CONFIG_PKE_TIMEOUT_IN_US 10000
#define CONFIG_TRNG_TIMEOUT_IN_US 10000
#define CONFIG_SYMC_WAIT_TIMEOUT_IN_US 1000000
#define CONFIG_SYMC_CLEAR_TIMEOUT_IN_US 10000
#define CONFIG_RKP_WAIT_TIMEOUT_IN_US 10000
#define CONFIG_KLAD_COM_ROUTE_TIMEOUT_IN_US 10000
#define CONFIG_OT_TYPE_SUPPORT 1

/*
 * Mbedtls Configuration
 */
// #define CONFIG_SYMC_HARDEN_INTERFACE_SUPPORT 1
// #define CONFIG_HASH_HARDEN_INTERFACE_SUPPORT 1

#if defined(CONFIG_HI3516CV610)
#define CONFIG_SYMC_192_SUPPORT 1
#define CONFIG_SYMC_BIT_WIDTH_1_SUPPORT 1
#define CONFIG_HASH_PBKDF2_SOFT_SUPPORT 1
#define CONFIG_SYMC_SM4_CFB_OFB_SUPPORT 1
#define CONFIG_KM_EFFECTIVE_KEY_SUPPORT 1
#define CONFIG_KM_KEYSLOT_SOFT_SUPPORT 1
#define CRYPTO_IOT_V200 1
#define CONFIG_HASH_VIRT_CHN_NUM 8
#define CONFIG_SYMC_VIRT_CHN_NUM 8
#define CONFIG_SPACC_NONALIGNED_ADDR_SUPPORT    1
#define CONFIG_SPACC_ADDR_ALIGN_LEN 1
#endif

#if defined(CONFIG_HI3519DV500)
#define CONFIG_HASH_SHA384_SUPPORT 1
#define CONFIG_HASH_SHA512_SUPPORT 1
#define CONFIG_HASH_PBKDF2_HARD_SUPPORT 1
#define CONFIG_KM_SESSION_KEY_SUPPORT 1
#define CONFIG_KM_CONTENT_KEY_SUPPORT 1
#define CONFIG_KM_ABRK1_SUPPORT 1
#define CONFIG_KM_ABRK2_SUPPORT 1
#define CONFIG_KM_ODRK1_SUPPORT 1
#define CONFIG_KM_DRK1_SUPPORT 1
#define CONFIG_KM_RDRK0_SUPPORT 1
#define CONFIG_KM_RDRK1_SUPPORT 1
#define CONFIG_KM_MDRK0_SUPPORT 1
#define CONFIG_KM_MDRK1_SUPPORT 1
#define CONFIG_KM_MDRK2_SUPPORT 1
#define CONFIG_KM_MDRK3_SUPPORT 1
#define CONFIG_KM_KEYSLOT_HARD_SUPPORT 1
#define CONFIG_PKE_SUPPORT_ECC_CURVE_25519 1
#define CONFIG_PKE_SUPPORT_ECC_ED25519 1
#define CONFIG_PKE_ECC_EDDSA_SIGN_SUPPORT 1
#define CONFIG_PKE_ECC_EDDSA_VERIFY_SUPPORT 1
#define CONFIG_KM_SM4_SUPPORT 1
#define CONFIG_HASH_VIRT_CHN_NUM 32
#define CONFIG_SYMC_VIRT_CHN_NUM 8
#define CONFIG_SPACC_ADDR_ALIGN_LEN 4
#endif

/*
 * Romable API Configuration
 */

/*
 * Test Configuration
 */
#define CONFIG_UT_SUPPORT 1

/*
 * Application Configuration
 */

/*
 * Log Configuration
 */
#define CONFIG_CRYPTO_LOG_INFO_DISABLE 1
#define CONFIG_CRYPTO_LOG_PTR_CHK_INFO_DISABLE 1

#endif /* CRYPTO_FEATURES_H */